version: "3.7"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    networks:
      - listmonk
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    #restart: unless-stopped
    volumes:
      - type: volume
        source: listmonk-data
        target: /var/lib/postgresql/data

  app:
    #restart: unless-stopped
    build: .
    ports:
      - "9000:9000"
    networks:
      - listmonk
    depends_on:
      - db
      - mailhog
    environment:
      - ROOT_URL=http://localhost:9000
      - FROM_EMAIL=hello@ivo-bathke.name
      - NOTIFY_EMAIL=
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=listmonk
      - DB_PW=listmonk
      - DB_NAME=listmonk
      - DB_SSL_MODE=disable
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_AUTH=cram
      - SMTP_USER=
      - SMTP_PW=

  mailhog:
    image: mailhog/mailhog:latest
    ports:
        - 1025:1025
        - 8025:8025
    networks:
      - listmonk
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - listmonk

networks:
  listmonk:

volumes:
  listmonk-data:
